version: 1.0.{build}
skip_tags: true
os: Windows Server 2012

install:
  - 'ECHO Install: %APPVEYOR_PULL_REQUEST_NUMBER%,%APPVEYOR_REPO_BRANCH%,'
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF "%APPVEYOR_REPO_BRANCH%" == "master" SET CreateBinaries=true

configuration: Release

build_script:
  - 'cd src'
  - '.nuget\nuget.exe restore'
  - 'msbuild.exe UnityRegistrationValidator.msbuild /p:BuildNumber=%appveyor_build_version%.0 /t:Packages'

artifacts:
  - path: src\*.nupkg
    name: NugetPackages

test: off

